from typing import Protocol, List, Dict, Any

class EmbeddingProvider(Protocol):
    def embed_documents(self, texts: List[str]) -> List[List[float]]: ...
    def embed_query(self, text: str) -> List[float]: ...

class VectorStore(Protocol):
    def add_documents(self, documents: List[Dict[str, Any]]): ...
    def search(self, query: str, top_k: int, threshold: float) -> List[Dict[str, Any]]: ...
